### Production environment settings

# STS role and target account
Sts.Role: arn:aws:iam::003342916324:role/admin

# Network settings
Stack.Inputs.VpcName: Default

# Application settings
Stack.Inputs.ApplicationDesiredCount: 2
Stack.Inputs.ApplicationImageId: ami-0b170143fdcd702d0
Stack.Inputs.ApplicationInstanceType: t2.micro
Stack.Inputs.KeyName: docker-production-aws

# Proxy settings
Stack.Inputs.ProxyImage: blankia/squid
Stack.Inputs.ProxyWhitelist: .dockerproductionaws.org
